//! Emits paired C and Rust programs that print struct layout data
//! (size, alignment, field offsets) in identical formats.
//!
//! CI compiles both, runs both, and diffs the output. Any mismatch
//! proves the generated Rust `#[repr(C)]` struct disagrees with the
//! real C Vulkan headers,the most dangerous class of FFI bug.
//!
//! Structs with bit-field members get size+align checks only (no field
//! offsets), since C `offsetof()` is undefined for bit-fields and the
//! packed Rust field names differ from C.

use std::collections::HashSet;

use crate::parse::{StructDef, VkRegistry};
use crate::resolve_types::{is_rust_keyword, member_name};

/// Structs to skip,opaque stubs without real C definitions.
fn is_opaque(name: &str) -> bool {
    name.starts_with("StdVideo")
}

/// Build the set of extension names to skip: any extension that requires
/// platform headers or targets Vulkan SC instead of standard Vulkan.
/// A plain `#include <vulkan/vulkan.h>` (no VK_USE_PLATFORM defines)
/// only provides types from platform-independent, standard-Vulkan extensions.
fn untestable_extensions(registry: &VkRegistry) -> HashSet<String> {
    registry
        .extensions
        .iter()
        .filter(|ext| {
            ext.platform.is_some() || !ext.supported.split(',').any(|p| p.trim() == "vulkan")
        })
        .map(|ext| ext.name.clone())
        .collect()
}

/// Returns true if this struct is available in standard vulkan.h.
fn is_testable(s: &StructDef, skip_extensions: &HashSet<String>) -> bool {
    if s.members.is_empty() || is_opaque(&s.name) {
        return false;
    }
    match &s.provided_by {
        Some(provider) => !skip_extensions.contains(provider) && !provider.starts_with("VKSC_"),
        // Types without provenance are from disabled or SC-only extensions
        None => false,
    }
}

/// Returns true if the struct has any bit-field members.
fn has_bitfields(s: &StructDef) -> bool {
    s.members.iter().any(|m| m.is_bitfield)
}

/// Fields to skip in offset checks,Rust keywords that `offset_of!` can't handle.
fn should_skip_field(field_name: &str) -> bool {
    is_rust_keyword(&member_name(field_name))
}

// ---------------------------------------------------------------------------
// C output
// ---------------------------------------------------------------------------

/// Generate a C program that prints layout data for every testable struct.
///
/// Output format (one line per struct):
/// ```text
/// StructName size align off0 off1 off2 ...
/// ```
/// Bitfield structs emit only size and align (no field offsets).
pub fn emit_c_layout_check(registry: &VkRegistry) -> String {
    let skip = untestable_extensions(registry);

    let mut c = String::new();
    c.push_str("// Auto-generated by the generator crate. Do not edit.\n");
    c.push_str("#include <vulkan/vulkan.h>\n");
    c.push_str("#include <stddef.h>\n");
    c.push_str("#include <stdio.h>\n\n");
    c.push_str("int main(void) {\n");

    for s in &registry.structs {
        if !is_testable(s, &skip) {
            continue;
        }

        let c_name = format!("Vk{}", s.name);
        let mut fmt_parts = vec!["%zu".to_string(), "%zu".to_string()];
        let mut arg_parts = vec![format!("sizeof({c_name})"), format!("_Alignof({c_name})")];

        if !has_bitfields(s) {
            let fields: Vec<&str> = s
                .members
                .iter()
                .map(|m| m.name.as_str())
                .filter(|n| !should_skip_field(n))
                .collect();

            for field in &fields {
                fmt_parts.push("%zu".to_string());
                arg_parts.push(format!("offsetof({c_name}, {field})"));
            }
        }

        let fmt = fmt_parts.join(" ");
        let args = arg_parts.join(", ");
        c.push_str(&format!("    printf(\"{} {fmt}\\n\", {args});\n", s.name));
    }

    c.push_str("    return 0;\n");
    c.push_str("}\n");
    c
}

// ---------------------------------------------------------------------------
// Rust output
// ---------------------------------------------------------------------------

/// Generate a Rust program that prints the same layout data as the C program.
pub fn emit_rust_layout_check(registry: &VkRegistry) -> String {
    let skip = untestable_extensions(registry);

    let mut rs = String::new();
    rs.push_str("// Auto-generated by the generator crate. Do not edit.\n");
    rs.push_str("use core::mem::{offset_of, size_of, align_of};\n");
    rs.push_str("use vulkan_rust_sys::structs;\n\n");
    rs.push_str("fn main() {\n");

    for s in &registry.structs {
        if !is_testable(s, &skip) {
            continue;
        }

        let rust_name = &s.name;
        let mut parts = vec![
            format!("size_of::<structs::{rust_name}>()"),
            format!("align_of::<structs::{rust_name}>()"),
        ];

        if !has_bitfields(s) {
            let fields: Vec<String> = s
                .members
                .iter()
                .map(|m| member_name(&m.name))
                .filter(|n| !is_rust_keyword(n))
                .collect();

            for field in &fields {
                parts.push(format!("offset_of!(structs::{rust_name}, {field})"));
            }
        }

        let print_args = parts.join(", ");
        let fmt = std::iter::repeat_n("{}", parts.len())
            .collect::<Vec<_>>()
            .join(" ");
        rs.push_str(&format!(
            "    println!(\"{rust_name} {fmt}\", {print_args});\n"
        ));
    }

    rs.push_str("}\n");
    rs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::{MemberDef, StructDef};

    fn make_member(name: &str) -> MemberDef {
        MemberDef {
            name: name.to_string(),
            type_name: "uint32_t".to_string(),
            is_pointer: false,
            is_const: false,
            is_double_pointer: false,
            array_size: None,
            optional: false,
            values: None,
            len: None,
            extern_sync: None,
            is_bitfield: false,
            bitwidth: None,
        }
    }

    fn make_bitfield(name: &str, bits: u8) -> MemberDef {
        MemberDef {
            is_bitfield: true,
            bitwidth: Some(bits),
            ..make_member(name)
        }
    }

    fn minimal_registry() -> VkRegistry {
        VkRegistry {
            structs: vec![StructDef {
                name: "Extent2D".to_string(),
                members: vec![make_member("width"), make_member("height")],
                extends: vec![],
                returned_only: false,
                is_union: false,
                provided_by: Some("VK_VERSION_1_0".to_string()),
            }],
            handles: vec![],
            enums: vec![],
            bitmasks: vec![],
            commands: vec![],
            constants: vec![],
            func_pointers: vec![],
            extensions: vec![],
            platforms: vec![],
            aliases: vec![],
            base_types: Default::default(),
        }
    }

    #[test]
    fn c_output_includes_struct_and_offsetof() {
        let c = emit_c_layout_check(&minimal_registry());
        assert!(c.contains("sizeof(VkExtent2D)"));
        assert!(c.contains("offsetof(VkExtent2D, width)"));
        assert!(c.contains("offsetof(VkExtent2D, height)"));
    }

    #[test]
    fn rust_output_includes_struct_and_offset_of() {
        let rs = emit_rust_layout_check(&minimal_registry());
        assert!(rs.contains("size_of::<structs::Extent2D>()"));
        assert!(rs.contains("offset_of!(structs::Extent2D, width)"));
        assert!(rs.contains("offset_of!(structs::Extent2D, height)"));
    }

    #[test]
    fn c_and_rust_output_same_struct_count() {
        let reg = minimal_registry();
        let c = emit_c_layout_check(&reg);
        let rs = emit_rust_layout_check(&reg);
        let c_lines = c.lines().filter(|l| l.contains("printf")).count();
        let rs_lines = rs.lines().filter(|l| l.contains("println")).count();
        assert_eq!(c_lines, rs_lines);
    }

    #[test]
    fn skips_keyword_fields_in_both_outputs() {
        let reg = VkRegistry {
            structs: vec![StructDef {
                name: "Foo".to_string(),
                members: vec![make_member("sType"), make_member("type")],
                extends: vec![],
                returned_only: false,
                is_union: false,
                provided_by: Some("VK_VERSION_1_0".to_string()),
            }],
            handles: vec![],
            enums: vec![],
            bitmasks: vec![],
            commands: vec![],
            constants: vec![],
            func_pointers: vec![],
            extensions: vec![],
            platforms: vec![],
            aliases: vec![],
            base_types: Default::default(),
        };
        let c = emit_c_layout_check(&reg);
        let rs = emit_rust_layout_check(&reg);
        assert!(!c.contains("offsetof(VkFoo, type)"));
        assert!(!rs.contains("offset_of!(structs::Foo, r#type)"));
        assert!(c.contains("offsetof(VkFoo, sType)"));
        assert!(rs.contains("offset_of!(structs::Foo, s_type)"));
    }

    #[test]
    fn bitfield_structs_get_size_only() {
        let reg = VkRegistry {
            structs: vec![StructDef {
                name: "BitfieldStruct".to_string(),
                members: vec![make_bitfield("fieldA", 24), make_bitfield("fieldB", 8)],
                extends: vec![],
                returned_only: false,
                is_union: false,
                provided_by: Some("VK_VERSION_1_0".to_string()),
            }],
            handles: vec![],
            enums: vec![],
            bitmasks: vec![],
            commands: vec![],
            constants: vec![],
            func_pointers: vec![],
            extensions: vec![],
            platforms: vec![],
            aliases: vec![],
            base_types: Default::default(),
        };
        let c = emit_c_layout_check(&reg);
        let rs = emit_rust_layout_check(&reg);
        // Size and align are checked
        assert!(c.contains("sizeof(VkBitfieldStruct)"));
        assert!(rs.contains("size_of::<structs::BitfieldStruct>()"));
        // No field offsets
        assert!(!c.contains("offsetof"));
        assert!(!rs.contains("offset_of!"));
    }

    #[test]
    fn untestable_extensions_filters_vulkansc_only() {
        use crate::parse::ExtensionDef;

        let reg = VkRegistry {
            extensions: vec![
                ExtensionDef {
                    name: "VK_KHR_swapchain".to_string(),
                    number: 1,
                    ext_type: None,
                    platform: None,
                    depends: None,
                    promoted_to: None,
                    deprecated_by: None,
                    supported: "vulkan".to_string(),
                    items: vec![],
                },
                ExtensionDef {
                    name: "VKSC_something".to_string(),
                    number: 2,
                    ext_type: None,
                    platform: None,
                    depends: None,
                    promoted_to: None,
                    deprecated_by: None,
                    supported: "vulkansc".to_string(),
                    items: vec![],
                },
                ExtensionDef {
                    name: "VK_KHR_both".to_string(),
                    number: 3,
                    ext_type: None,
                    platform: None,
                    depends: None,
                    promoted_to: None,
                    deprecated_by: None,
                    supported: "vulkan,vulkansc".to_string(),
                    items: vec![],
                },
                ExtensionDef {
                    name: "VK_KHR_wayland".to_string(),
                    number: 4,
                    ext_type: None,
                    platform: Some("wayland".to_string()),
                    depends: None,
                    promoted_to: None,
                    deprecated_by: None,
                    supported: "vulkan".to_string(),
                    items: vec![],
                },
            ],
            structs: vec![],
            handles: vec![],
            enums: vec![],
            bitmasks: vec![],
            commands: vec![],
            constants: vec![],
            func_pointers: vec![],
            platforms: vec![],
            aliases: vec![],
            base_types: Default::default(),
        };
        let skip = untestable_extensions(&reg);
        assert!(
            !skip.contains("VK_KHR_swapchain"),
            "standard vulkan should pass"
        );
        assert!(
            skip.contains("VKSC_something"),
            "vulkansc-only should be skipped"
        );
        assert!(!skip.contains("VK_KHR_both"), "vulkan,vulkansc should pass");
        assert!(
            skip.contains("VK_KHR_wayland"),
            "platform extension should be skipped"
        );
    }
}
