//! Emits paired C and Rust programs that print struct layout data
//! (size, alignment, field offsets) in identical formats.
//!
//! CI compiles both, runs both, and diffs the output. Any mismatch
//! proves the generated Rust `#[repr(C)]` struct disagrees with the
//! real C Vulkan headers — the most dangerous class of FFI bug.

use std::collections::HashSet;

use crate::parse::{StructDef, VkRegistry};
use crate::resolve_types::{is_rust_keyword, member_name};

/// Structs to skip — opaque stubs without real C definitions.
fn is_opaque(name: &str) -> bool {
    name.starts_with("StdVideo")
}

/// Build the set of extension names to skip: any extension that requires
/// platform headers or targets Vulkan SC instead of standard Vulkan.
/// A plain `#include <vulkan/vulkan.h>` (no VK_USE_PLATFORM defines)
/// only provides types from platform-independent, standard-Vulkan extensions.
fn untestable_extensions(registry: &VkRegistry) -> HashSet<String> {
    registry
        .extensions
        .iter()
        .filter(|ext| {
            ext.platform.is_some()
                || !ext.supported.contains("vulkan")
                || ext.supported == "vulkansc"
        })
        .map(|ext| ext.name.clone())
        .collect()
}

/// Returns true if the struct has any bit-field members.
/// `offsetof()` is undefined for C bit-fields.
fn has_bitfields(s: &StructDef) -> bool {
    s.members.iter().any(|m| m.is_bitfield)
}

/// Filter structs to only those testable with a plain `#include <vulkan/vulkan.h>`.
fn testable_structs<'a>(
    registry: &'a VkRegistry,
    skip_extensions: &HashSet<String>,
) -> Vec<&'a StructDef> {
    registry
        .structs
        .iter()
        .filter(|s| !s.members.is_empty())
        .filter(|s| !is_opaque(&s.name))
        .filter(|s| !has_bitfields(s))
        .filter(|s| match &s.provided_by {
            Some(provider) => !skip_extensions.contains(provider) && !provider.starts_with("VKSC_"),
            None => true,
        })
        .collect()
}

/// Fields to skip in offset checks — Rust keywords that `offset_of!` can't handle.
fn should_skip_field(field_name: &str) -> bool {
    is_rust_keyword(&member_name(field_name))
}

// ---------------------------------------------------------------------------
// C output
// ---------------------------------------------------------------------------

/// Generate a C program that prints layout data for every testable struct.
///
/// Output format (one line per struct):
/// ```text
/// StructName size align off0 off1 off2 ...
/// ```
pub fn emit_c_layout_check(registry: &VkRegistry) -> String {
    let skip = untestable_extensions(registry);
    let structs = testable_structs(registry, &skip);

    let mut c = String::new();
    c.push_str("// Auto-generated by the generator crate. Do not edit.\n");
    c.push_str("#include <vulkan/vulkan.h>\n");
    c.push_str("#include <stddef.h>\n");
    c.push_str("#include <stdio.h>\n\n");
    c.push_str("int main(void) {\n");

    for s in &structs {
        let c_name = format!("Vk{}", s.name);

        // Build the printf format and args for fields.
        let fields: Vec<&str> = s
            .members
            .iter()
            .map(|m| m.name.as_str())
            .filter(|n| !should_skip_field(n))
            .collect();

        let mut fmt_parts = vec!["%zu".to_string(), "%zu".to_string()]; // size, align
        let mut arg_parts = vec![format!("sizeof({c_name})"), format!("_Alignof({c_name})")];

        for field in &fields {
            fmt_parts.push("%zu".to_string());
            arg_parts.push(format!("offsetof({c_name}, {field})"));
        }

        let fmt = fmt_parts.join(" ");
        let args = arg_parts.join(", ");
        c.push_str(&format!("    printf(\"{} {fmt}\\n\", {args});\n", s.name));
    }

    c.push_str("    return 0;\n");
    c.push_str("}\n");
    c
}

// ---------------------------------------------------------------------------
// Rust output
// ---------------------------------------------------------------------------

/// Generate a Rust program that prints the same layout data as the C program.
pub fn emit_rust_layout_check(registry: &VkRegistry) -> String {
    let skip = untestable_extensions(registry);
    let structs = testable_structs(registry, &skip);

    let mut rs = String::new();
    rs.push_str("// Auto-generated by the generator crate. Do not edit.\n");
    rs.push_str("use core::mem::{offset_of, size_of, align_of};\n");
    rs.push_str("use vk_sys::structs;\n\n");
    rs.push_str("fn main() {\n");

    for s in &structs {
        let rust_name = &s.name;

        let fields: Vec<String> = s
            .members
            .iter()
            .map(|m| member_name(&m.name))
            .filter(|n| !is_rust_keyword(n))
            .collect();

        let mut parts = vec![
            format!("size_of::<structs::{rust_name}>()"),
            format!("align_of::<structs::{rust_name}>()"),
        ];
        for field in &fields {
            parts.push(format!("offset_of!(structs::{rust_name}, {field})"));
        }

        let print_args = parts.join(", ");
        let fmt = std::iter::repeat_n("{}", parts.len())
            .collect::<Vec<_>>()
            .join(" ");
        rs.push_str(&format!(
            "    println!(\"{rust_name} {fmt}\", {print_args});\n"
        ));
    }

    rs.push_str("}\n");
    rs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse::{MemberDef, StructDef};

    fn make_member(name: &str) -> MemberDef {
        MemberDef {
            name: name.to_string(),
            type_name: "uint32_t".to_string(),
            is_pointer: false,
            is_const: false,
            is_double_pointer: false,
            array_size: None,
            optional: false,
            values: None,
            len: None,
            extern_sync: None,
            is_bitfield: false,
        }
    }

    fn minimal_registry() -> VkRegistry {
        VkRegistry {
            structs: vec![StructDef {
                name: "Extent2D".to_string(),
                members: vec![make_member("width"), make_member("height")],
                extends: vec![],
                returned_only: false,
                is_union: false,
                provided_by: None,
            }],
            handles: vec![],
            enums: vec![],
            bitmasks: vec![],
            commands: vec![],
            constants: vec![],
            func_pointers: vec![],
            extensions: vec![],
            platforms: vec![],
            aliases: vec![],
            base_types: Default::default(),
        }
    }

    #[test]
    fn c_output_includes_struct_and_offsetof() {
        let c = emit_c_layout_check(&minimal_registry());
        assert!(c.contains("sizeof(VkExtent2D)"));
        assert!(c.contains("offsetof(VkExtent2D, width)"));
        assert!(c.contains("offsetof(VkExtent2D, height)"));
    }

    #[test]
    fn rust_output_includes_struct_and_offset_of() {
        let rs = emit_rust_layout_check(&minimal_registry());
        assert!(rs.contains("size_of::<structs::Extent2D>()"));
        assert!(rs.contains("offset_of!(structs::Extent2D, width)"));
        assert!(rs.contains("offset_of!(structs::Extent2D, height)"));
    }

    #[test]
    fn c_and_rust_output_same_struct_count() {
        let reg = minimal_registry();
        let c = emit_c_layout_check(&reg);
        let rs = emit_rust_layout_check(&reg);
        let c_lines = c.lines().filter(|l| l.contains("printf")).count();
        let rs_lines = rs.lines().filter(|l| l.contains("println")).count();
        assert_eq!(c_lines, rs_lines);
    }

    #[test]
    fn skips_keyword_fields_in_both_outputs() {
        let reg = VkRegistry {
            structs: vec![StructDef {
                name: "Foo".to_string(),
                members: vec![make_member("sType"), make_member("type")],
                extends: vec![],
                returned_only: false,
                is_union: false,
                provided_by: None,
            }],
            handles: vec![],
            enums: vec![],
            bitmasks: vec![],
            commands: vec![],
            constants: vec![],
            func_pointers: vec![],
            extensions: vec![],
            platforms: vec![],
            aliases: vec![],
            base_types: Default::default(),
        };
        let c = emit_c_layout_check(&reg);
        let rs = emit_rust_layout_check(&reg);
        // "type" field should be skipped in both
        assert!(!c.contains("offsetof(VkFoo, type)"));
        assert!(!rs.contains("offset_of!(structs::Foo, r#type)"));
        // s_type should still be present
        assert!(c.contains("offsetof(VkFoo, sType)"));
        assert!(rs.contains("offset_of!(structs::Foo, s_type)"));
    }
}
